---
- hosts: all
  become: true
  gather_facts: false
  
  vars_prompt:  
    - name: "uname"
      prompt: "What is the username to reset password(mandatory)?"
      private: no
    - name: "password"
      prompt: "What is the new username password(mandatory)?"
      private: no  

  
  roles:
    - password_reset
