---

- block:
    - name: list ALL users
      shell: | 
        awk -F':' '{print "groupname: " $1 " gid: " $3 " grouplist: " $4}' /etc/group
      register: out  
    - debug: var=out.stdout_lines
  when: ggroup | default("") == ""
  
- block:   
    - name: list user
      shell: | 
        awk -F':' '{print "groupname: " $1 " gid: " $3 " grouplist: " $4}' /etc/group | grep {{ ggroup }}
      register: out
      ignore_errors: true
    - debug: var=out.stdout_lines 
  when: ggroup | default("") != ""  